### ISSUE TITLE
No module named 'PIL

### ISSUE THREAD

**Issue by kenassash** [nnagibator228/PoizonBotPlatform#1]
Добрый день.

После установки poizonbotplatform на главной странице date.spase пишет ошибку:

`Error Type:
ModuleNotFoundError

Error Message:
No module named 'PIL'

Logs:
Stack Trace:
  File "/opt/python/detalib/debugger.py", line 131, in wrap
    return func(event, context)

  File "/var/task/_entry.py", line 13, in handler
    import main  # noqa

  File "/var/task/main.py", line 21, in 
    from EmojiCaptcha import EmojiCaptcha

  File "/var/task/EmojiCaptcha.py", line 6, in 
    from PIL import Image`

Как установить данный модуль?

**Comment by nnagibator228** [comment]
Добрый, модуль Pillow уже добавлен в `requirements.txt`, в некоторых установках иногда требуется использовать  модуль Image, я также внес его в `requirements.txt`

Замените ```from PIL import Image ``` на `import Image` в шестой строке файла _EmojiCaptcha.py_:

```python
File "/var/task/EmojiCaptcha.py", line 6, in
from PIL import Image`
```

Прошу, дайте знать, если это сработает, тогда я изменю этот фрагмент кода в новом релизе.  😄
